source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ADGCloudKit_Example', :exclusive => true do
  pod "ADGCloudKit", :path => "../"
end

target 'ADGCloudKit_Tests', :exclusive => true do
  pod "ADGCloudKit", :path => "../"

  
end
